### ISSUE TITLE
Host this on PyPI and conda-forge

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#153]
IMO this is dependent on #92 and #85 being addressed satisfactorily. Should be doable soon.

- [x] [Host on PyPI](https://pypi.org/project/qurro/)
- [x] Host on conda-forge (just test that Qurro is importable)
- [ ] Host on conda-forge (run full test suite?)

So a complication with the full-test-suite thing is that the python tests rely on Q2 being installed... that'll make life hard.

Note that per #74, these should require that the min python version is 3.5.3

**Comment by fedarko** [comment]
https://test.pypi.org/project/qurro/

**Comment by fedarko** [comment]
looks like in order to do things cleanly for conda forge, it'll be easiest to make tests output to a `tests/output/` directory like before *and then* move outputs to `docs/demos`. That'll make it easier to run tests in the meta.yaml.

**Comment by mortonjt** [comment]
you don't need to have comprehensive tests run on conda-forge.  A good first pass is to just make sure that qurro can be imported.

**Comment by fedarko** [comment]
i guess that's fair! i would like to run the tests if possible, just to verify that stuff isn't completely broken. but i'll see about just getting a cursory conda-forge build set up sometime in the future, maybe adding in the test suite at a later point
