### ISSUE TITLE
Remove reliance on songbird for the differentials type in the future

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#154]
When https://github.com/qiime2/q2-types/pull/212 is merged into a release of QIIME 2 (probs the next one, i.e. 2019.7), we can just require that at least that version of QIIME 2 is used with Qurro and remove our reliance on Songbird to define the Q2 `FeatureData[Differential]` type.

Along with letting us clean up some complex/ugly code in `plugin_setup.py`, this will impact the example jupyter notebook(s?), `.travis.yml` (no need to install songbird during the testing process), and some documentation I think. All in all this will make using Qurro easier.

**Comment by thermokarst** [comment]
BTW, one thing you can do in your .travis config is update [this](https://github.com/fedarko/qurro/blob/master/.travis.yml#L24) to use a "dev env" version of QIIME 2 - then you will be able to test changes like the ones in qiime2/q2-types#212 right after the PR is merged (and [busywork](https://busywork.qiime2.org) spits out a new dev env).

**Comment by thermokarst** [comment]
Sorry, forgot the dev env link: https://dev.qiime2.org/latest/quickstart/

**Comment by fedarko** [comment]
I had no idea that existed—this is really useful for immediately testing with the latest Q2 version. Thanks Matt!

(I'm working on a dev branch of Qurro r/n but these changes should be merged back into master within a week or so)
