### ISSUE TITLE
How to cite qurro

### ISSUE THREAD

**Issue by manuss11** [biocore/qurro#169]
Hi, thanks for developing qurro, I want to cite it, but I don't know how!

**Comment by fedarko** [comment]
Thanks so much for using Qurro!

We're still working on a manuscript for this tool, so there isn't a corresponding paper out yet. In the meantime, however, I've linked Qurro's code on GitHub with [Zenodo](https://zenodo.org/): so for now you can cite Qurro's DOI on Zenodo by using this link: https://doi.org/10.5281/zenodo.3257763. (Scroll down to the bottom of the page for citation instructions.) This link should also be available in Qurro's README now.

I'm going to leave this issue open for the time being—I'll close it when a corresponding paper citation for Qurro is ready (probably a few months from now at minimum).

Thanks again for using Qurro, and please let us know if you have any questions/comments/etc.!

**Comment by fedarko** [comment]
Just for reference -- the preferred citation for now is our bioRxiv preprint on Qurro (see [here](https://github.com/biocore/qurro#citing-qurro) for citation info). I'll close this issue when this preprint winds up in a journal eventually :)
