### ISSUE TITLE
Set zero = false by default in vega-lite for sample plot

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#218]

**Comment by mortonjt** [comment]
Would this add in the possibility of pseudocounts?  There are some scenarios where this can be very helpful.

An even better option would be to add in uncertainty via Dirichilet bootstrapping.  One possibility is you perform bootstrapping (with like 100 replicates), and then pass in the means / stds.  That way you can also plot error vars in the balance scatter plots to help measure the uncertainty.

**Comment by fedarko** [comment]
Hey, sorry for taking forever to respond—was out of the lab for a few days there.

This particular issue doesn't really relate to pseudocounts (that's in #208, as you noticed :)—this particular issue is just a graphical thing (whether or not to scale the sample plot so that x=0 and y=0 are always shown, which was previously the default but won't be done in the next release of Qurro).

Thanks for the code example! I'm not *sure* I understand what you mean by using bootstrapping here. This'd just give error bars for each particular count, which we'd incorporate in the sample plot (when drawn as a scatterplot) for each sample?

We can continue discussion in #222 :)
