### ISSUE TITLE
Clearer label for the rank plot y-axis

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#223]
Currently, the rank plot y-axis just says `Magnitude: [ranking column name]`.

`[ranking column name]` can be either a differential name—examples:
- `Magnitude: C(sample_type_body_site, Treatment(sea water))(T: fish GI)`
- `Magnitude: Intercept`
- `Magnitude: effect`
- `Magnitude: Oxygen`

...or a feature loading axis name—
- `Magnitude: Axis 1`
- `Magnitude: Axis 2`
- `Magnitude: Axis 3`

A way to make this legend slightly more understandable would be changing "`Magnitude`" to either `Differential` or `Feature Loading`, based on the input ranking type:
- `Differential: C(sample_type_body_site, Treatment(sea water))(T: fish GI)`
- `Differential: Intercept`
- `Differential: effect`
- `Differential: Oxygen`
- `Feature Loading: Axis 1`
- `Feature Loading: Axis 2`
- `Feature Loading: Axis 3`

Programmatically, this should be simple enough to implement (on the python side of things, just chuck the y-axis label prefix somewhere into the rank plot JSON; on the JS side of things, detect it in the rank plot JSON and store it as a property of the loaded `RRVDisplay` instance).

@cameronmartino @mortonjt does this seem mathematically kosher / helpful?

**Comment by mortonjt** [comment]
@fedarko that seems reasonable to me
