### ISSUE TITLE
Add "Classic QIIME Colors" color scheme for categorical data

### ISSUE THREAD

**Issue by fedarko** [biocore/qurro#300]
Just a small little detail that will make Qurro more consistent with Emperor (and, soon, Empress (https://github.com/biocore/empress/issues/137)).

I think we can just use [`vega.scheme()`](https://vega.github.io/vega/docs/schemes/#registering-additional-schemes) to do this.

Suggested by @ElDeveloper.

**Comment by fedarko** [comment]
![image](https://user-images.githubusercontent.com/4177727/80407055-dab5f680-8879-11ea-8684-20e88629018f.png)

![image](https://user-images.githubusercontent.com/4177727/80407084-e6092200-8879-11ea-90bd-25c340e967de.png)

@ElDeveloper told you it wouldn't take too long ;) :shipit:

**Comment by ElDeveloper** [comment]
Looks great!
