### ISSUE TITLE
species level

### ISSUE THREAD

**Issue by pavlo888** [biocore/qurro#310]
Hi, 

I am very happy with the results I have obtained from my data analysis using qurro. However, I was wondering if it would be safe to make inferences down to species level? 

I am interested in evaluating the ratios between some species of interest in my dataset. 

Cheers, 
Pablo

**Comment by fedarko** [comment]
Not sure what you mean by inferences, sorry -- are you asking if it's safe to use species-level taxonomic annotations as ways to select features for a log-ratio?

I think this will depend mostly on how your data was generated. If it's 16S marker gene sequencing data, then my understanding is that species-level taxonomic annotations are generally thought to be unreliable, so I wouldn't read too much into them. It's still totally possible to search for species in Qurro (and I guess it could be useful to do this in certain cases, for example if you're really sure that the species annotations you're using are correct), but I'd normally favor using at least genus-level annotations instead here. On the other hand, if it's shotgun metagenomics data, then species annotations are a lot more defensible.

**Comment by pavlo888** [comment]
Hi Fedarko, 

Thank you for your reply. I was indeed wondering if I could go down to genus-level annotations with my data that is 16S marker gene sequencing.

Cheers, 
Pablo
